# Generated by Django 4.2.6 on 2024-12-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_jumbezawateja'),
    ]

    operations = [
        migrations.AddField(
            model_name='watejawote',
            name='Wamemaliza_Hawajakopa_Tena',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
