# Generated by Django 4.2.6 on 2024-12-12 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_watejawote_wamemaliza_hawajakopa_tena'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarejeshoCopiesTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, max_length=100000, null=True, verbose_name='Namba Ya Mteja')),
                ('JinaKamiliLaMteja', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Kamili La Mteja')),
                ('JinaLaKituo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina La Kituo Cha Mteja')),
                ('SimuYaMteja', models.IntegerField(blank=True, null=True, verbose_name='Namba Ya Simu Ya Mteja')),
                ('EmailYaMteja', models.EmailField(blank=True, max_length=500, null=True, verbose_name='Email Ya Mteja')),
                ('Mahali', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mahali Anapoishi')),
                ('KiasiAnachokopa', models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Anachokopa')),
                ('KiasiAlicholipa', models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Alicholipa')),
                ('RejeshoKwaSiku', models.IntegerField(blank=True, default=0, null=True, verbose_name='Rejesho Kwa Siku')),
                ('JumlaYaDeni', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Deni Analodaiwa')),
                ('Riba', models.IntegerField(blank=True, default=0, null=True, verbose_name='Riba')),
                ('RejeshoLililoPokelewaLeo', models.IntegerField(blank=True, default=0, null=True, verbose_name='Rejesho Lililo Pokelewa Leo')),
                ('FainiKwaSiku', models.IntegerField(blank=True, default=0, null=True, verbose_name='Faini Kwa Siku')),
                ('AmesajiliwaNa', models.CharField(blank=True, max_length=500, null=True, verbose_name='Amesajiliwa Na ?')),
                ('PichaYaMteja', models.ImageField(blank=True, null=True, upload_to='media/PichaZaVyakula/', verbose_name='Picha Ya Mteja')),
                ('Ni_Mteja_Hai', models.BooleanField(blank=True, default=True, null=True)),
                ('Created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Up_To', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Marejesho Copies Two',
            },
        ),
    ]
