# Generated by Django 4.2.6 on 2024-12-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_marejeshocopiestwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='watejawote',
            name='AinaZaMarejesho',
            field=models.CharField(blank=True, choices=[('Kila Siku', 'Kila Siku'), ('Baada Ya Mwezi', 'Baada Ya Mwezi')], max_length=500, null=True, verbose_name='Aina Za Marejesho'),
        ),
    ]
